### ISSUE TITLE
环境变量配置好后，运行 npm run watch 一直卡在这里，没有跳出二维码，这什么什么原因？

### ISSUE THREAD

**Issue by cosyong** [aoao-eth/wechat-ai-summarize-bot#14]
root@iZrj9edam6o1jdr7ev3yesZ:~/wechat-ai-summarize-bot# npm run watch
npm WARN config init.module Use `--init-module` instead.

> wechat-summarize-bot@0.0.1 watch
> npx ts-node ./src/main.ts

npm WARN config init.module Use `--init-module` instead.leted in 6ms
(⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠦ : timing config:load:flatten Completed in 6ms

**Comment by aoao-eth** [comment]
GPT 回答：
这个警告是由于在npm config命令中使用了过时的init.module选项而触发的。这个选项已经被替换为--init-module。

如果你想避免这个警告，你可以使用最新版本的npm，或者在config命令中使用--init-module选项，而不是init.module选项。例如： 

```
npm config --init-module=/path/to/config.js
```

这将使用指定的config.js文件来初始化npm配置。
