### ISSUE TITLE
启动报错ERR [PadLocalClient] Fail to get server info: Error: 3 INVALID_ARGUMENT: [tid:7952e6da] token is to long, max length allowed: 50

### ISSUE THREAD

**Issue by yintiankuaile** [aoao-eth/wechat-ai-summarize-bot#17]
启动报错
![image](https://github.com/aoao-eth/wechat-ai-summarize-bot/assets/21208901/a649124e-c770-42e2-8e90-87c312f01f2d)
ERR [PadLocalClient] Fail to get server info: Error: 3 INVALID_ARGUMENT: [tid:7952e6da] token is to long, max length allowed: 50

**Comment by aoao-eth** [comment]
token is to long, max length allowed: 50

**Comment by aoao-eth** [comment]
padleft token 填错了？

**Comment by yintiankuaile** [comment]
![image](https://github.com/aoao-eth/wechat-ai-summarize-bot/assets/21208901/5e621bc0-ea2a-48a8-b3b9-6bd9cee591a1)
不是这个生成的token吗？我是填在项目的配置文件里了啊
![image](https://github.com/aoao-eth/wechat-ai-summarize-bot/assets/21208901/3935b5b7-7b39-4bb4-8869-504f9fcfbcd7)

**Comment by aoao-eth** [comment]
这个不是 js 文件，不能这样写

xxx=xxxx 后面不带引号，也不带分号

**Comment by yintiankuaile** [comment]
啊，好吧，习惯性了
