### ISSUE TITLE
总结是报错：总结失败：Request failed with status code 400

### ISSUE THREAD

**Issue by ruhaiai** [aoao-eth/wechat-ai-summarize-bot#21]

**Comment by ruhaiai** [comment]
总结失败，错误代码400

**Comment by chaojieChen225** [comment]
我也是总结失败。。

**Comment by aoao-eth** [comment]
![image](https://github.com/aoao-eth/wechat-ai-summarize-bot/assets/897401/44a265b1-1b6c-4b80-80b8-e17c9d3cce92)

![image](https://github.com/aoao-eth/wechat-ai-summarize-bot/assets/897401/70cb8159-85f6-495c-a172-fad28f30518f)

**Comment by aoao-eth** [comment]
@chaojieChen225 @ruhaiai @inwikipedia @baiyutang

**Comment by shitongbin** [comment]
还是不行。。。

**Comment by shitongbin** [comment]
把输入参数query 改成input_content，再改成段落OK

**Comment by aoao-eth** [comment]
ok 我改下文档
