### ISSUE TITLE
针对同步信息过来的数据，一旦错误自动退出进程（相当于ctrl+C），message类型特别多，这种容错加try catch是否合适？有好的error捕获方案吗？

### ISSUE THREAD

**Issue by inwikipedia** [aoao-eth/wechat-ai-summarize-bot#9]
![image](https://github.com/aoao-eth/wechat-summarize-bot/assets/644260/448c2bd9-7b2e-4f59-847c-c4a28cf5b858)

**Comment by aoao-eth** [comment]
通常不会退出，这个是因为 PadLocal 服务出问题了，这时候已经收不到新消息了，直接退出没什么问题

**Comment by inwikipedia** [comment]
那一般是保持进程常在，直接执行npm run watch ,PadLocal 服务出问题后，相当于ctr+c，难道要用pm2进程守护方式吗？

**Comment by aoao-eth** [comment]
这个时候其实需要人工介入，这个错误是因为有两个实例在运行连接了同一个 pad left token，需要人工介入才能解决，pm2 也解决不了

**Comment by aoao-eth** [comment]
给 watch 命令加了 pm2
